name: Deploy to Minikube

on:
  push:
    branches:
      - master  # master 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker

      - name: Decode Secrets
        run: |
          echo "${{ secrets.USERNAME_SECRET }}" | base64 --decode > username.txt
          echo "${{ secrets.PASSWORD_SECRET }}" | base64 --decode > password.txt

      - name: Build and push Docker image
        run: |
          
          DOCKER_USER=$(cat username.txt)
          DOCKER_PASS=$(cat password.txt)

          docker build -t $DOCKER_USER/my-nginx-app:latest .

          
          echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
          
          
          docker push $DOCKER_USER/my-nginx-app:latest

      - name: Deploy to Minikube
        run: |
          
          kubectl get deployment nginx-test || kubectl create deployment nginx-test --image=$DOCKER_USER/my-nginx-app:latest
          
          
          kubectl set image deployment/nginx-test nginx=$DOCKER_USER/my-nginx-app:latest
          
          
          kubectl rollout status deployment/nginx-test --timeout=120s || kubectl get pods -o wide
