name: Deploy to Minikube

on:
  push:
    branches:
      - master  # master 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker

      - name: Build and push Docker image
        run: |
          # Docker 빌드
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-nginx-app:latest .
          
          # Docker Hub 로그인 (보안 방식 적용)
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          
          # 빌드된 이미지 푸시
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-nginx-app:latest

      - name: Deploy to Minikube
        run: |
          # Deployment 존재 여부 확인 후 생성
          kubectl get deployment nginx-test || kubectl create deployment nginx-test --image=${{ secrets.DOCKERHUB_USERNAME }}/my-nginx-app:latest
          
          # Deployment 업데이트
          kubectl set image deployment/nginx-test nginx=${{ secrets.DOCKERHUB_USERNAME }}/my-nginx-app:latest
          
          # 즉시 롤아웃 상태 확인
          kubectl rollout status deployment/nginx-test --timeout=120s || kubectl get pods -o wide

      - name: Wait for deployment to be ready
        run: |
          # 2분 내로 롤아웃 완료되지 않으면 에러 처리
          kubectl rollout status deployment/nginx-test --timeout=120s || (echo "Deployment failed!" && exit 1)

      - name: Get Minikube Service URL
        run: |
          # Minikube에서 서비스 URL 확인
          minikube service nginx-test --url
