name: Deploy to Minikube

on:
  push:
    branches:
      - master  # master 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker

      # Actions 예시 (빌드 & 푸시)
      - name: Build and push Docker image
        run: |
          docker build -t <dockerhub-username>/my-nginx-app:latest .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push <dockerhub-username>/my-nginx-app:latest
      - name: Deploy to Minikube
        run: |
          kubectl set image deployment/nginx-test nginx=<dockerhub-username>/my-nginx-app:latest
          kubectl rollout status deployment/nginx-test
      

      - name: Wait for deployment to be ready
        run: |
          # 2분 내로 롤아웃 완료되지 않으면 에러 처리
          kubectl rollout status deployment/nginx-test --timeout=120s || kubectl get pods -o wide

      - name: Forward port for local access
        run: |
          # 백그라운드에서 포트포워딩 수행 후 5초 대기
          nohup kubectl port-forward service/nginx-test 8080:80 &
          sleep 5
          echo "Service accessible at http://127.0.0.1:8080"
