name: Deploy to Minikube

on:
  push:
    branches:
      - master  # master 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker

      - name: Build Docker image
        run: |
          docker build -t my-nginx-app .
          # Minikube에 직접 이미지 로드 (빌드 완료 후 my-nginx-app을 강제로 인식시키기)
          minikube image load my-nginx-app

      - name: Deploy to Minikube
        run: |
          kubectl delete deployment nginx-test --ignore-not-found=true
          kubectl delete service nginx-test --ignore-not-found=true
          kubectl create deployment nginx-test --image=my-nginx-app
          kubectl expose deployment nginx-test --type=NodePort --port=80

      - name: Wait for deployment to be ready
        run: |
          # 2분 내로 롤아웃 완료되지 않으면 에러 처리
          kubectl rollout status deployment/nginx-test --timeout=120s || kubectl get pods -o wide

      - name: Forward port for local access
        run: |
          # 백그라운드에서 포트포워딩 수행 후 5초 대기
          nohup kubectl port-forward service/nginx-test 8080:80 &
          sleep 5
          echo "Service accessible at http://127.0.0.1:8080"
